"""Frozen schema baseline, including adoption of pre-Alembic installations."""

import sqlalchemy as sa
from alembic import op

from app.db.legacy_migration import adopt_index, adopt_table

revision = "20260914_01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    adopt_table(
        "system_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    adopt_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("hashed_password", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "manager", "analyst", "viewer", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "restricted_to_projects", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "must_change_password", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    adopt_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    adopt_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    adopt_table(
        "api_keys",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("hashed_key", sa.String(length=128), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_api_keys_hashed_key"), "api_keys", ["hashed_key"], unique=True)
    adopt_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    adopt_index(op.f("ix_api_keys_prefix"), "api_keys", ["prefix"], unique=False)
    adopt_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    adopt_table(
        "audit_logs",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("user_email", sa.String(length=320), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    adopt_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    adopt_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    adopt_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    adopt_table(
        "jobs",
        sa.Column(
            "job_type",
            sa.Enum("ingest", "sync", "export", "monitor", "quality", "rscript", name="job_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "success", "failed", "cancelled", name="job_status"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=80), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_jobs_id"), "jobs", ["id"], unique=False)
    adopt_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    adopt_table(
        "notifications",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False)
    adopt_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    adopt_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    adopt_table(
        "projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "paused", "closed", name="project_status"), nullable=False
        ),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    adopt_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    adopt_table(
        "boundary_layers",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("source_format", sa.String(length=20), nullable=False),
        sa.Column("source_filename", sa.String(length=300), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("feature_count", sa.Integer(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("bbox", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_boundary_layers_id"), "boundary_layers", ["id"], unique=False)
    adopt_index(
        op.f("ix_boundary_layers_project_id"), "boundary_layers", ["project_id"], unique=False
    )
    adopt_table(
        "connections",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("workspace", sa.String(length=120), nullable=False),
        sa.Column("username", sa.String(length=200), nullable=False),
        sa.Column("password_encrypted", sa.Text(), nullable=False),
        sa.Column("verify_ssl", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("sync_interval_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "export_format",
            sa.Enum("stata", "tabular", "spss", name="export_format"),
            nullable=False,
        ),
        sa.Column(
            "sync_mode", sa.String(length=20), server_default=sa.text("'interval'"), nullable=False
        ),
        sa.Column("sync_times", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column(
            "sync_timezone", sa.String(length=60), server_default=sa.text("'UTC'"), nullable=False
        ),
        sa.Column("questionnaires", sa.JSON(), nullable=False),
        sa.Column("interview_status", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_sync_status",
            sa.Enum("never", "running", "success", "failed", name="sync_status"),
            nullable=False,
        ),
        sa.Column("last_sync_error", sa.Text(), nullable=False),
        sa.Column("server_info", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_connections_id"), "connections", ["id"], unique=False)
    adopt_index(op.f("ix_connections_project_id"), "connections", ["project_id"], unique=False)
    adopt_table(
        "dashboards",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("pages", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column(
            "theme", sa.String(length=40), server_default=sa.text("'default'"), nullable=False
        ),
        sa.Column("appearance", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("public_token", sa.String(length=64), nullable=True),
        sa.Column("public_hostname", sa.String(length=253), nullable=True),
        sa.Column("drilldown", sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("refresh_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_dashboards_id"), "dashboards", ["id"], unique=False)
    adopt_index(op.f("ix_dashboards_project_id"), "dashboards", ["project_id"], unique=False)
    adopt_index(
        op.f("ix_dashboards_public_hostname"), "dashboards", ["public_hostname"], unique=True
    )
    adopt_index(op.f("ix_dashboards_public_token"), "dashboards", ["public_token"], unique=True)
    adopt_index(op.f("ix_dashboards_slug"), "dashboards", ["slug"], unique=True)
    adopt_table(
        "html_snippets",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_html_snippets_id"), "html_snippets", ["id"], unique=False)
    adopt_index(op.f("ix_html_snippets_project_id"), "html_snippets", ["project_id"], unique=False)
    adopt_table(
        "project_members",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "manager", "analyst", "viewer", name="user_role"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_member"),
    )
    adopt_index(op.f("ix_project_members_id"), "project_members", ["id"], unique=False)
    adopt_index(
        op.f("ix_project_members_project_id"), "project_members", ["project_id"], unique=False
    )
    adopt_index(op.f("ix_project_members_user_id"), "project_members", ["user_id"], unique=False)
    adopt_table(
        "project_scripts",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("run_on_import", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_ok", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_output", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_project_scripts_id"), "project_scripts", ["id"], unique=False)
    adopt_index(
        op.f("ix_project_scripts_project_id"), "project_scripts", ["project_id"], unique=False
    )
    adopt_table(
        "dashboard_views",
        sa.Column("dashboard_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("state", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_shared", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dashboard_id"], ["dashboards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(
        op.f("ix_dashboard_views_dashboard_id"), "dashboard_views", ["dashboard_id"], unique=False
    )
    adopt_index(op.f("ix_dashboard_views_id"), "dashboard_views", ["id"], unique=False)
    adopt_table(
        "datasets",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("upload", "survey_solutions", "derived", name="dataset_source"),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(length=500), nullable=False),
        sa.Column("connection_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "ready", "failed", name="dataset_status"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=False),
        sa.Column("column_count", sa.Integer(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("derivation", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["connection_id"], ["connections.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_datasets_connection_id"), "datasets", ["connection_id"], unique=False)
    adopt_index(op.f("ix_datasets_id"), "datasets", ["id"], unique=False)
    adopt_index(op.f("ix_datasets_project_id"), "datasets", ["project_id"], unique=False)
    adopt_index(op.f("ix_datasets_slug"), "datasets", ["slug"], unique=True)
    adopt_table(
        "share_links",
        sa.Column("dashboard_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("last_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dashboard_id"], ["dashboards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_share_links_dashboard_id"), "share_links", ["dashboard_id"], unique=False)
    adopt_index(op.f("ix_share_links_id"), "share_links", ["id"], unique=False)
    adopt_index(op.f("ix_share_links_token"), "share_links", ["token"], unique=True)
    adopt_table(
        "sync_runs",
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("questionnaire", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum("never", "running", "success", "failed", name="sync_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_imported", sa.Integer(), nullable=False),
        sa.Column("datasets_created", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("log", sa.JSON(), nullable=False),
        sa.Column(
            "archive_path", sa.String(length=500), server_default=sa.text("''"), nullable=False
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_sync_runs_connection_id"), "sync_runs", ["connection_id"], unique=False)
    adopt_index(op.f("ix_sync_runs_id"), "sync_runs", ["id"], unique=False)
    adopt_table(
        "charts",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column(
            "chart_type",
            sa.Enum(
                "bar",
                "horizontal_bar",
                "stacked_bar",
                "line",
                "area",
                "pie",
                "donut",
                "scatter",
                "table",
                "kpi",
                "heatmap",
                "crosstab",
                "map",
                "gauge",
                "horizontal_stacked_bar",
                "population_pyramid",
                "funnel",
                "boxplot",
                name="chart_type",
            ),
            nullable=False,
        ),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_charts_dataset_id"), "charts", ["dataset_id"], unique=False)
    adopt_index(op.f("ix_charts_id"), "charts", ["id"], unique=False)
    adopt_table(
        "dataset_relationships",
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("left_dataset_id", sa.String(length=36), nullable=False),
        sa.Column("right_dataset_id", sa.String(length=36), nullable=False),
        sa.Column("left_variable", sa.String(length=300), nullable=False),
        sa.Column("right_variable", sa.String(length=300), nullable=False),
        sa.Column(
            "cardinality",
            sa.Enum(
                "one_to_one",
                "one_to_many",
                "many_to_one",
                "many_to_many",
                name="relationship_cardinality",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("detected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["left_dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["right_dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "left_dataset_id",
            "right_dataset_id",
            "left_variable",
            "right_variable",
            name="uq_dataset_relationship",
        ),
    )
    adopt_index(op.f("ix_dataset_relationships_id"), "dataset_relationships", ["id"], unique=False)
    adopt_index(
        op.f("ix_dataset_relationships_left_dataset_id"),
        "dataset_relationships",
        ["left_dataset_id"],
        unique=False,
    )
    adopt_index(
        op.f("ix_dataset_relationships_project_id"),
        "dataset_relationships",
        ["project_id"],
        unique=False,
    )
    adopt_index(
        op.f("ix_dataset_relationships_right_dataset_id"),
        "dataset_relationships",
        ["right_dataset_id"],
        unique=False,
    )
    adopt_table(
        "indicators",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("value_format", sa.String(length=40), nullable=False),
        sa.Column("target_value", sa.Float(), nullable=True),
        sa.Column("warning_threshold", sa.Float(), nullable=True),
        sa.Column("critical_threshold", sa.Float(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("higher_is_better", "lower_is_better", "neutral", name="indicator_direction"),
            nullable=False,
        ),
        sa.Column("breakdown_variable", sa.String(length=300), nullable=False),
        sa.Column("breakdown_targets", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("percent_of", sa.String(length=20), server_default=sa.text("''"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("last_value", sa.Float(), nullable=True),
        sa.Column("last_computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_indicators_dataset_id"), "indicators", ["dataset_id"], unique=False)
    adopt_index(op.f("ix_indicators_id"), "indicators", ["id"], unique=False)
    adopt_table(
        "quality_rules",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column(
            "check_type",
            sa.Enum(
                "missing_rate",
                "value_range",
                "duplicates",
                "outliers",
                "consistency",
                "interview_duration",
                "gps_missing",
                "constant_value",
                name="check_type",
            ),
            nullable=False,
        ),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("filters", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "critical", name="alert_severity"),
            nullable=False,
        ),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_quality_rules_dataset_id"), "quality_rules", ["dataset_id"], unique=False)
    adopt_index(op.f("ix_quality_rules_id"), "quality_rules", ["id"], unique=False)
    adopt_table(
        "saved_queries",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_saved_queries_dataset_id"), "saved_queries", ["dataset_id"], unique=False)
    adopt_index(op.f("ix_saved_queries_id"), "saved_queries", ["id"], unique=False)
    adopt_table(
        "variables",
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column(
            "var_type",
            sa.Enum("numeric", "categorical", "text", "datetime", "boolean", name="variable_type"),
            nullable=False,
        ),
        sa.Column("storage_type", sa.String(length=50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("n_missing", sa.BigInteger(), nullable=False),
        sa.Column("n_unique", sa.BigInteger(), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("mean_value", sa.Float(), nullable=True),
        sa.Column("value_labels", sa.JSON(), nullable=False),
        sa.Column("missing_tags", sa.JSON(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_variables_dataset_id"), "variables", ["dataset_id"], unique=False)
    adopt_index(op.f("ix_variables_id"), "variables", ["id"], unique=False)
    adopt_index(op.f("ix_variables_name"), "variables", ["name"], unique=False)
    adopt_table(
        "alert_rules",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("indicator_id", sa.String(length=36), nullable=True),
        sa.Column("dataset_id", sa.String(length=36), nullable=True),
        sa.Column("condition", sa.JSON(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "critical", name="alert_severity"),
            nullable=False,
        ),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("recipients", sa.JSON(), nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["indicator_id"], ["indicators.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_alert_rules_dataset_id"), "alert_rules", ["dataset_id"], unique=False)
    adopt_index(op.f("ix_alert_rules_id"), "alert_rules", ["id"], unique=False)
    adopt_index(op.f("ix_alert_rules_indicator_id"), "alert_rules", ["indicator_id"], unique=False)
    adopt_table(
        "indicator_snapshots",
        sa.Column("indicator_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("breakdown", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["indicator_id"], ["indicators.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(
        op.f("ix_indicator_snapshots_computed_at"),
        "indicator_snapshots",
        ["computed_at"],
        unique=False,
    )
    adopt_index(op.f("ix_indicator_snapshots_id"), "indicator_snapshots", ["id"], unique=False)
    adopt_index(
        op.f("ix_indicator_snapshots_indicator_id"),
        "indicator_snapshots",
        ["indicator_id"],
        unique=False,
    )
    adopt_table(
        "quality_results",
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("failed_rows", sa.BigInteger(), nullable=False),
        sa.Column("total_rows", sa.BigInteger(), nullable=False),
        sa.Column("failure_rate", sa.Float(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["quality_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_quality_results_id"), "quality_results", ["id"], unique=False)
    adopt_index(op.f("ix_quality_results_rule_id"), "quality_results", ["rule_id"], unique=False)
    adopt_index(op.f("ix_quality_results_run_at"), "quality_results", ["run_at"], unique=False)
    adopt_table(
        "widgets",
        sa.Column("dashboard_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "widget_type",
            sa.Enum(
                "chart",
                "table",
                "kpi",
                "indicator",
                "text",
                "crosstab",
                "quality",
                "countdown",
                "map",
                "html",
                "freshness",
                name="widget_type",
            ),
            nullable=False,
        ),
        sa.Column("chart_id", sa.String(length=36), nullable=True),
        sa.Column("indicator_id", sa.String(length=36), nullable=True),
        sa.Column("dataset_id", sa.String(length=36), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("layout", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("page", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["chart_id"], ["charts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dashboard_id"], ["dashboards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["indicator_id"], ["indicators.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_widgets_dashboard_id"), "widgets", ["dashboard_id"], unique=False)
    adopt_index(op.f("ix_widgets_id"), "widgets", ["id"], unique=False)
    adopt_table(
        "alerts",
        sa.Column("rule_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "critical", name="alert_severity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "acknowledged", "resolved", name="alert_status"),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=36), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False)
    adopt_index(op.f("ix_alerts_id"), "alerts", ["id"], unique=False)
    adopt_index(op.f("ix_alerts_rule_id"), "alerts", ["rule_id"], unique=False)
    adopt_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    adopt_table(
        "widget_comments",
        sa.Column("dashboard_id", sa.String(length=36), nullable=False),
        sa.Column("widget_id", sa.String(length=36), nullable=False),
        sa.Column("view_id", sa.String(length=36), nullable=True),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dashboard_id"], ["dashboards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["widget_comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["view_id"], ["dashboard_views.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["widget_id"], ["widgets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    adopt_index(
        op.f("ix_widget_comments_dashboard_id"), "widget_comments", ["dashboard_id"], unique=False
    )
    adopt_index(op.f("ix_widget_comments_id"), "widget_comments", ["id"], unique=False)
    adopt_index(
        op.f("ix_widget_comments_parent_id"), "widget_comments", ["parent_id"], unique=False
    )
    adopt_index(op.f("ix_widget_comments_view_id"), "widget_comments", ["view_id"], unique=False)
    adopt_index(
        op.f("ix_widget_comments_widget_id"), "widget_comments", ["widget_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Restore a verified pre-upgrade backup to downgrade the baseline")
